# KOL handles configuration for Apify-based X ingestion
# Priority: this file is used first; if empty or missing, code falls back to .env X_KOL_HANDLES
# handle values are Twitter screen names without '@'

kol:
  - handle: elonmusk
  - handle: cryptocom
  - handle: cz_binance
  - handle: pumpdotfun
  - handle: okx
  - handle: HuobiGlobal
  - handle: binance
  - handle: FLOKI
  - handle: realDonaldTrump
  - handle: Gate
  - handle: dogecoin
  - handle: BNBCHAIN
  - handle: JinseFinance
  - handle: a16z
  - handle: cointelegraph
  - handle: Shibtoken
  - handle: BabyDogeCoin
  - handle: justinsuntron
  - handle: coinbase
  - handle: Bitcoin
  - handle: trondao
  - handle: crypto_birb
  - handle: kaitrump
  - handle: BlueMove_OA
  - handle: heyibinance
  - handle: horizenglobal
  - handle: grok
  - handle: HyperliquidX
  - handle: liangxihuigui
  - handle: sunyuchentron
  - handle: EricTrump
  - handle: DonaldJTrumpJr
  - handle: worldlibertyfi
  - handle: GetTrumpMemes
  - handle: LaraLeaTrump
  - handle: bwenews
  - handle: TrumpWarRoom
  - handle: tedcruz
  - handle: USDai_Official
  - handle: ethereum
  - handle: VitalikButerin
  - handle: solana
  - handle: star_okx
  - handle: FoxNews
  - handle: quant_network
  - handle: gverdian
  - handle: coinglass_com
