kol:
  - handle: elonmusk
  - handle: whale_alert
  - handle: cryptocom
  - handle: binance
  - handle: coinbase
  - handle: CryptoGuru
  - handle: VitalikButerin
  - handle: cz_binance
  - handle: SBF_FTX
  - handle: APompliano
  - handle: aantonop
  - handle: coindesk
  - handle: Cointelegraph
  - handle: TheBlock__
  - handle: DefiPulse
